
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hdann
 */
public class Main extends javax.swing.JFrame {

    static int serie;
    static Date fecha;
    static Color color;
    static String material;
    static RAM ram;
    static DiscoDuro disco;
    static Bateria bateria;
    static Teclado teclado;
    static Pantalla pantalla;
    static Procesador procesador;
    
    static ArrayList<Computadora> computadoras = new ArrayList();
    static ArrayList<Tecnico> tecnicos = new ArrayList();

    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crudCompu = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AgregarC = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfSerie = new javax.swing.JTextField();
        dcFecha = new com.toedter.calendar.JDateChooser();
        bColor = new javax.swing.JButton();
        tfMaterial = new javax.swing.JTextField();
        aRAM = new javax.swing.JButton();
        aDisco = new javax.swing.JButton();
        aBateria = new javax.swing.JButton();
        aTeclado = new javax.swing.JButton();
        aPantalla = new javax.swing.JButton();
        aProcesador = new javax.swing.JButton();
        aCompu = new javax.swing.JButton();
        ModC = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cbCompus = new javax.swing.JComboBox<>();
        bActualizar = new javax.swing.JButton();
        bMD = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfSerie2 = new javax.swing.JTextField();
        dcFecha2 = new com.toedter.calendar.JDateChooser();
        bColor2 = new javax.swing.JButton();
        tfMaterial2 = new javax.swing.JTextField();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        crudTecnico = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNombreT = new javax.swing.JTextField();
        sEdadT = new javax.swing.JSpinner();
        cbGeneroT = new javax.swing.JComboBox<>();
        bAgregarT = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfNombreT2 = new javax.swing.JTextField();
        sEdadT2 = new javax.swing.JSpinner();
        cbGeneroT2 = new javax.swing.JComboBox<>();
        cbTecnicos = new javax.swing.JComboBox<>();
        bActualizarT = new javax.swing.JButton();
        bModificarT = new javax.swing.JButton();
        bEliminarT = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bCRUD_T = new javax.swing.JButton();
        bEnsamblaje = new javax.swing.JButton();
        bCRUD_C = new javax.swing.JButton();

        crudCompu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Serie");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Color");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Material");

        bColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bColorMouseClicked(evt);
            }
        });

        aRAM.setText("Agregar RAM");
        aRAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aRAMMouseClicked(evt);
            }
        });

        aDisco.setText("Agregar Disco");
        aDisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aDiscoMouseClicked(evt);
            }
        });

        aBateria.setText("Agregar Bateria");
        aBateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aBateriaMouseClicked(evt);
            }
        });

        aTeclado.setText("Agregar Teclado");
        aTeclado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aTecladoMouseClicked(evt);
            }
        });

        aPantalla.setText("Agregar Pantalla");
        aPantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aPantallaMouseClicked(evt);
            }
        });

        aProcesador.setText("Agregar Procesador");
        aProcesador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aProcesadorMouseClicked(evt);
            }
        });

        aCompu.setText("Agregar");
        aCompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aCompuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSerie)
                    .addComponent(bColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfMaterial))
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aRAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aBateria, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aProcesador)))
                    .addComponent(aCompu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aRAM)
                    .addComponent(aTeclado))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aDisco)
                            .addComponent(aPantalla))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(bColor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aBateria)
                            .addComponent(aProcesador))))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aCompu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AgregarCLayout = new javax.swing.GroupLayout(AgregarC);
        AgregarC.setLayout(AgregarCLayout);
        AgregarCLayout.setHorizontalGroup(
            AgregarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AgregarCLayout.setVerticalGroup(
            AgregarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Agregar", AgregarC);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        bActualizar.setText("Actualizar");
        bActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bActualizarMouseClicked(evt);
            }
        });

        bMD.setText("Mostrar Datos");
        bMD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMDMouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Serie");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Color");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Material");

        bColor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bColor2MouseClicked(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bModificarMouseClicked(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbCompus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(bActualizar)
                        .addGap(38, 38, 38)
                        .addComponent(bMD)
                        .addGap(49, 49, 49)
                        .addComponent(bModificar)
                        .addGap(45, 45, 45)
                        .addComponent(bEliminar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSerie2)
                            .addComponent(dcFecha2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(bColor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfMaterial2))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCompus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bActualizar)
                            .addComponent(bMD)
                            .addComponent(bModificar)
                            .addComponent(bEliminar))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfSerie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel7))
                    .addComponent(dcFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ModCLayout = new javax.swing.GroupLayout(ModC);
        ModC.setLayout(ModCLayout);
        ModCLayout.setHorizontalGroup(
            ModCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ModCLayout.setVerticalGroup(
            ModCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar", ModC);

        crudCompu.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Edad");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Genero");

        cbGeneroT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        bAgregarT.setText("Agregar");
        bAgregarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAgregarTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAgregarT)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombreT)
                            .addComponent(sEdadT)
                            .addComponent(cbGeneroT, 0, 102, Short.MAX_VALUE))))
                .addContainerGap(581, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sEdadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbGeneroT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(bAgregarT)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Agregar", jPanel4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Edad");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Genero");

        cbGeneroT2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        bActualizarT.setText("Actualizar");
        bActualizarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bActualizarTMouseClicked(evt);
            }
        });

        bModificarT.setText("Modificar");
        bModificarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bModificarTMouseClicked(evt);
            }
        });

        bEliminarT.setText("Eliminar");
        bEliminarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEliminarTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cbTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(bActualizarT)
                        .addGap(43, 43, 43)
                        .addComponent(bModificarT)
                        .addGap(34, 34, 34)
                        .addComponent(bEliminarT))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombreT2)
                            .addComponent(sEdadT2)
                            .addComponent(cbGeneroT2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bActualizarT)
                    .addComponent(bModificarT)
                    .addComponent(bEliminarT))
                .addGap(107, 107, 107)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfNombreT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel14))
                    .addComponent(sEdadT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbGeneroT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Modificar", jPanel5);

        javax.swing.GroupLayout crudTecnicoLayout = new javax.swing.GroupLayout(crudTecnico.getContentPane());
        crudTecnico.getContentPane().setLayout(crudTecnicoLayout);
        crudTecnicoLayout.setHorizontalGroup(
            crudTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        crudTecnicoLayout.setVerticalGroup(
            crudTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Examen II P2");

        bCRUD_T.setText("CRUD Tecnico");

        bEnsamblaje.setText("Ensamblaje");

        bCRUD_C.setText("CRUD Computadora");
        bCRUD_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCRUD_CMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(bCRUD_C)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bCRUD_T, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(bEnsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCRUD_C, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCRUD_T, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEnsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(325, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aCompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aCompuMouseClicked
        serie = Integer.parseInt(tfSerie.getText());
        fecha = dcFecha.getDate();
        color = bColor.getBackground();
        material = tfMaterial.getText();
        
        Computadora c = new Computadora(serie, fecha, color, material, ram, disco, bateria, teclado, pantalla, procesador);
        computadoras.add(c);
    }//GEN-LAST:event_aCompuMouseClicked

    private void bColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bColorMouseClicked
        bColor.setBackground(JColorChooser.showDialog(crudCompu, "Ingrese color", Color.black));
    }//GEN-LAST:event_bColorMouseClicked

    private void bCRUD_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCRUD_CMouseClicked
        crudCompu.pack();
        crudCompu.setLocationRelativeTo(this);
        crudCompu.setVisible(true);
    }//GEN-LAST:event_bCRUD_CMouseClicked

    private void aRAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aRAMMouseClicked
        ram = new RAM(Integer.parseInt(JOptionPane.showInputDialog(crudCompu, "Ingrese tamano")),
                JOptionPane.showInputDialog(crudCompu, "Ingrese marca"), 3);
    }//GEN-LAST:event_aRAMMouseClicked

    private void aDiscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aDiscoMouseClicked
        disco = new DiscoDuro(Integer.parseInt(JOptionPane.showInputDialog(crudCompu, "Ingrese tamano")),
                JOptionPane.showInputDialog(crudCompu, "Ingrese marca"), 3);
    }//GEN-LAST:event_aDiscoMouseClicked

    private void aBateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aBateriaMouseClicked
        bateria = new Bateria(Integer.parseInt(JOptionPane.showInputDialog(crudCompu, "Ingrese capacidad")),
                JOptionPane.showInputDialog(crudCompu, "Ingrese material"),
                2);
    }//GEN-LAST:event_aBateriaMouseClicked

    private void aTecladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aTecladoMouseClicked
        teclado = new Teclado(JOptionPane.showInputDialog(crudCompu, "Ingrese material"),
        JColorChooser.showDialog(crudCompu, "Ingrese color", Color.black), 2);
    }//GEN-LAST:event_aTecladoMouseClicked

    private void aPantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aPantallaMouseClicked
        int temp = JOptionPane.showConfirmDialog(crudCompu, "La pantalla es tactil?");
        String tipo = JOptionPane.showInputDialog(crudCompu, "Ingrese tipo");
        if (temp == 0){
            pantalla = new Pantalla(true, tipo, 4);
        } else {
            pantalla = new Pantalla(false, tipo, 4);
        }
    }//GEN-LAST:event_aPantallaMouseClicked

    private void aProcesadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aProcesadorMouseClicked
        procesador = new Procesador(Integer.parseInt(JOptionPane.showInputDialog(crudCompu)),
        JOptionPane.showInputDialog(crudCompu, "Ingrese velocidad"), 3);
    }//GEN-LAST:event_aProcesadorMouseClicked

    private void bActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bActualizarMouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbCompus.getModel();
        for (Computadora computadora : computadoras) {
            modelo.addElement(computadora);
        }
    }//GEN-LAST:event_bActualizarMouseClicked

    private void bColor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bColor2MouseClicked
        bColor2.setBackground(JColorChooser.showDialog(crudCompu, "Ingrese color", Color.black));
    }//GEN-LAST:event_bColor2MouseClicked

    private void bMDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMDMouseClicked
        Computadora c = (Computadora) cbCompus.getSelectedItem();
        tfSerie2.setText(Integer.toString(c.getSerie()));
        dcFecha2.setDate(c.getFecha());
        bColor2.setBackground(c.getColor());
        tfMaterial2.setText(c.getMaterial());
    }//GEN-LAST:event_bMDMouseClicked

    private void bModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModificarMouseClicked
        int index = cbCompus.getSelectedIndex();
        Computadora c = new Computadora(Integer.parseInt(tfSerie2.getText()), dcFecha2.getDate(),
                bColor2.getBackground(), tfMaterial2.getText(), ram, disco, bateria, teclado, pantalla, procesador);
        computadoras.set(index, c);
    }//GEN-LAST:event_bModificarMouseClicked

    private void bEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEliminarMouseClicked
        int index = cbCompus.getSelectedIndex();
        computadoras.remove(index);
    }//GEN-LAST:event_bEliminarMouseClicked

    private void bAgregarTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAgregarTMouseClicked
        Tecnico t = new Tecnico(tfNombreT.getText(), (int) sEdadT.getValue(), (String) cbGeneroT.getSelectedItem(), 0);
        tecnicos.add(t);
    }//GEN-LAST:event_bAgregarTMouseClicked

    private void bActualizarTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bActualizarTMouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbTecnicos.getModel();
        for (Tecnico tecnico : tecnicos) {
            modelo.addElement(tecnico);
        }
    }//GEN-LAST:event_bActualizarTMouseClicked

    private void bModificarTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModificarTMouseClicked
        int index = cbTecnicos.getSelectedIndex();
        Tecnico t = new Tecnico(tfNombreT.getText(), (int) sEdadT.getValue(), (String) cbGeneroT.getSelectedItem(), 0);
        tecnicos.set(index, t);
    }//GEN-LAST:event_bModificarTMouseClicked

    private void bEliminarTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEliminarTMouseClicked
        int index = cbTecnicos.getSelectedIndex();
        tecnicos.remove(index);
    }//GEN-LAST:event_bEliminarTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarC;
    private javax.swing.JPanel ModC;
    private javax.swing.JButton aBateria;
    private javax.swing.JButton aCompu;
    private javax.swing.JButton aDisco;
    private javax.swing.JButton aPantalla;
    private javax.swing.JButton aProcesador;
    private javax.swing.JButton aRAM;
    private javax.swing.JButton aTeclado;
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bActualizarT;
    private javax.swing.JButton bAgregarT;
    private javax.swing.JButton bCRUD_C;
    private javax.swing.JButton bCRUD_T;
    private javax.swing.JButton bColor;
    private javax.swing.JButton bColor2;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bEliminarT;
    private javax.swing.JButton bEnsamblaje;
    private javax.swing.JButton bMD;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bModificarT;
    private javax.swing.JComboBox<String> cbCompus;
    private javax.swing.JComboBox<String> cbGeneroT;
    private javax.swing.JComboBox<String> cbGeneroT2;
    private javax.swing.JComboBox<String> cbTecnicos;
    private javax.swing.JDialog crudCompu;
    private javax.swing.JDialog crudTecnico;
    private com.toedter.calendar.JDateChooser dcFecha;
    private com.toedter.calendar.JDateChooser dcFecha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JSpinner sEdadT;
    private javax.swing.JSpinner sEdadT2;
    private javax.swing.JTextField tfMaterial;
    private javax.swing.JTextField tfMaterial2;
    private javax.swing.JTextField tfNombreT;
    private javax.swing.JTextField tfNombreT2;
    private javax.swing.JTextField tfSerie;
    private javax.swing.JTextField tfSerie2;
    // End of variables declaration//GEN-END:variables
}
